# -*- coding: utf-8 -*-
"""Gradio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1He6_gGGEGJCcvl0v8jGD49JFxbtj04cy

Implementation of Gradio
"""

pip install gradio

import gradio as gr

def get_inputs(E1, px1, py1, pz1, pt1, eta1, phi1, Q1, E2, px2, py2, pz2, pt2, eta2, phi2, Q2):
    input_features = np.array([E1, px1, py1, pz1, pt1, eta1, phi1, Q1, E2, px2, py2, pz2, pt2, eta2, phi2, Q2])
    input_features = input_features.reshape(1, -1)
    input_tensor = torch.tensor(input_features, dtype=torch.float32)
    with torch.no_grad():
        pred = model(input_tensor)

    return pred.item()

demo = gr.Interface(
    fn=get_inputs,
    inputs=['number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number' ],
    outputs='number'
    )
demo.launch(debug=True,share=True)